# Site settings
title: Viral Jogani
description: >
    Hi, I'm Viral Jogani, and I'm currently studying Electrical and Computer Engineering at Rutgers University. Here you'll find my thoughts on entrepreneurship, design, and anything else I find interesting.
author: Viral Jogani
email: viraljogani@gmail.com
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://blog.viraljogani.com" # the base hostname & protocol for your site
twitter_username: virjog
github_username:  virjog

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title
sass:
    style: compressed
